export const environment = {
  production: false,
  baseUrl: 'http://localhost:3000/api',
  configBaseUrl: 'http://localhost:3002',
  webApiBaseUrl: 'http://192.168.225.216:8081',
  apiEndPoint: {
    getAllDevice: '/getDevices',
    GetPorts: '/GetPorts',
    GetCard: '/GetCard',
    GetShelf: '/GetShelf',
    GetLink: '/GetLink',
    GetSlot: '/GetSlot',
    getMenu: '/getPageGroupPages',
    createPage: '/getTabsAndElements',
  },
  configApiEndPoint: {
    getDevice: '/getAllDevice',
    dashboardDeviceCounts: '/dashboardDeviceCounts',
    getAllDeviceGroup: '/getAllDeviceGroup',
    getAllDeviceCommand: '/getAllDeviceCommand',
    getAllDeviceFrequency: '/getAllDeviceFrequency',
    getUsers: '/getUsers',
    getCompareFilesInfo: '/getCompareFilesInfo',
  },
  uid: '7',
  orderid: '1',
};
